name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [10, 11]
        driver: [swoole, openswoole, 'roadrunner/frankenphp']
        exclude:
          - php: 8.1
            laravel: 11
          - php: 8.4
            laravel: 10
          - php: 8.4
            driver: openswoole

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.driver }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, ${{ matrix.driver != 'roadrunner/frankenphp' && matrix.driver || '' }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Show extension info
        run: |
          php --ri ${{ matrix.driver }}
        if: matrix.driver != 'roadrunner/frankenphp'

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="laravel/framework:^${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecations --fail-on-deprecation
